# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := WolpertingerStandalone WolpertingerVST

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

WolpertingerStandalone: 
	@echo ==== Building WolpertingerStandalone ====
	@${MAKE} --no-print-directory -C . -f WolpertingerStandalone.make

WolpertingerVST: 
	@echo ==== Building WolpertingerVST ====
	@${MAKE} --no-print-directory -C . -f WolpertingerVST.make

clean:
	@${MAKE} --no-print-directory -C . -f WolpertingerStandalone.make clean
	@${MAKE} --no-print-directory -C . -f WolpertingerVST.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   WolpertingerStandalone"
	@echo "   WolpertingerVST"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
